edition = "2018"
max_width = 160
indent_style = "Block"
reorder_imports = true
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
merge_imports = false
merge_derives = true
force_multiline_blocks = false
reorder_modules = true
reorder_impl_items = false
space_after_colon = true
tab_spaces = 4
trailing_comma = "Never"
use_try_shorthand = true
format_code_in_doc_comments = true
binop_separator = "Front"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
overflow_delimited_expr = true
report_fixme = "Always"
struct_lit_single_line = false