[development]
address = "0.0.0.0"
port = 8081
workers = 8
log = "normal"

[staging]
address = "0.0.0.0"
port = 8081
workers = 8
log = "normal"

[production]
address = "0.0.0.0"
port = 8081
workers = 8
log = "critical"
